# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQK8PUZdqXlneKLiHVT6839XULQ_tPs_
"""

import pandas as pd

# -------- INPUT FILES --------
X1_FILE = "W13.xlsx"   # contains Locus column
X2_FILE = "W13 Gene positions.xlsx"   # contains Locus, Start, End
OUTPUT_FILE = "X3_extracted_positions.xlsx"

# -------- READ EXCEL FILES --------
df_x1 = pd.read_excel(X1_FILE)
df_x2 = pd.read_excel(X2_FILE)

# -------- SANITY CHECK --------
required_x1 = {"Locus"}
required_x2 = {"Locus", "Start", "End"}

if not required_x1.issubset(df_x1.columns):
    raise ValueError("X1 file must contain column: Locus")

if not required_x2.issubset(df_x2.columns):
    raise ValueError("X2 file must contain columns: Locus, Start, End")

# -------- MERGE DATA --------
merged_df = pd.merge(
    df_x1,
    df_x2[["Locus", "Start", "End"]],
    on="Locus",
    how="left"
)

# -------- SAVE OUTPUT --------
merged_df.to_excel(OUTPUT_FILE, index=False)

print(f"Done! Extracted positions saved to: {OUTPUT_FILE}")
print(f"Total genes in X1: {len(df_x1)}")
print(f"Matched genes: {merged_df['Start'].notna().sum()}")
print(f"Unmatched genes: {merged_df['Start'].isna().sum()}")